name: Codespell

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: codespell-project/actions-codespell@v2
        with:
          skip: "*.git,*.png,*.jpg,go.sum,vendor,*.egg-info"
