"""Pack workspace: Dockerfile scaffold and agent_metadata.yaml."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agentcube.models.pack_models import MetadataOptions
from agentcube.services.metadata_service import AgentMetadata, MetadataService

DEFAULT_DOCKERFILE = """# Generated by AgentCube pack
FROM {base_image}
WORKDIR /app
COPY . /app
ENV PYTHONUNBUFFERED=1
EXPOSE {port}
{cmd_line}
"""


class PackRuntime:
    """Prepare a workspace for container build."""

    def pack(self, workspace_path: str | Path, **options: Any) -> dict[str, Any]:
        """
        Ensure Dockerfile exists and write agent_metadata.yaml from options.

        Returns a result dict with paths and flags.
        """
        root = Path(workspace_path).resolve()
        if not root.is_dir():
            raise FileNotFoundError(f"Workspace not found: {root}")

        meta_opts = MetadataOptions.from_options(options)
        svc = MetadataService(root)
        metadata = AgentMetadata(
            name=meta_opts.name,
            version=meta_opts.version,
            description=meta_opts.description,
            author=meta_opts.author,
            base_image=meta_opts.base_image,
            port=meta_opts.port,
            entrypoint=meta_opts.entrypoint,
            cmd=meta_opts.cmd,
            env=dict(meta_opts.env),
            labels=dict(meta_opts.labels),
            image=meta_opts.image or "",
            namespace=meta_opts.namespace,
        )
        svc.save_metadata(metadata)

        dockerfile = root / "Dockerfile"
        created_dockerfile = False
        if not dockerfile.is_file():
            if meta_opts.cmd:
                cmd_line = f"CMD {json.dumps(meta_opts.cmd)}"
            else:
                cmd_line = f'CMD ["python", "-m", "http.server", "{meta_opts.port}"]'
            content = DEFAULT_DOCKERFILE.format(
                base_image=meta_opts.base_image,
                port=meta_opts.port,
                cmd_line=cmd_line,
            )
            dockerfile.write_text(content, encoding="utf-8")
            created_dockerfile = True

        return {
            "workspace": str(root),
            "metadata_path": str(svc.metadata_path),
            "dockerfile_path": str(dockerfile),
            "created_dockerfile": created_dockerfile,
        }
