apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentcube

resources:
  - namespace.yaml
  - serviceaccounts/workloadmanager.yaml
  - serviceaccounts/router.yaml
  - serviceaccounts/volcano-scheduler.yaml
  - clusterroles/workloadmanager.yaml
  - clusterroles/volcano-scheduler.yaml
  - clusterrolebindings/workloadmanager.yaml
  - clusterrolebindings/volcano-scheduler.yaml
  - roles/router.yaml
  - rolebindings/router.yaml

commonLabels:
  app.kubernetes.io/part-of: agentcube
  app.kubernetes.io/managed-by: kustomize
